name: Build and deploy Node.js app to Azure Web App - leafacademy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Ensure Node.js version matches the requirements of Remix Run

      - name: npm install, build, and test
        run: |
          npm install
          npm run build  # Assuming your build script is configured in package.json

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Ensure proper permissions are set

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A72DDF7E3C024C3092206824F71C0ED6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9C9EE14E4B5D4F9AA7C92673F12C9816 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7EC46FC8A0E64B14BAB1928B1B2DD196 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "leafacademy"
          slot-name: "Production" # Ensure this matches your Azure Web App slot name
          package: . # Deploy the contents of the extracted artifact directory

